### ISSUE TITLE
Cannot install GADMTools

### ISSUE THREAD

**Issue by paddysmith99** [toledobastos/spatialsocialmedia#1]
Hello,

I'm having issues with installing GADMTools. I'm aware GADMTools has been removed from CRAN repository. I've tried to install the latest version using: 

remotes::install_version("GADMTools", "3.9-1")

However it is still not working. Any help would be appreciated.

Cheers!

**Comment by toledobastos** [comment]
There's a GitHub repo for [GADMTools ](https://github.com/cran/GADMTools). You should be able to install it locally. It's indeed a requirement for this package.

**Comment by paddysmith99** [comment]
Are you able to provide line of code for this? 

I've tried installing GADMTools through:
 _remotes::install_github("IamKDO/GADMTools")_ 

and getting the error: _Error in loadNamespace(x) : there is no package called ‘GADMTools’_ when trying to plot using GADM. 

Bit of an R amateur so having difficulties, the rest of the code is running well.

Thanks

**Comment by paddysmith99** [comment]
This is the error message I am receiving

> devtools::install_github("IamKDO/GADMTools")
Downloading GitHub repo IamKDO/GADMTools@HEAD
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                          
2: CRAN packages only           
3: None                         
4: vctrs (0.6.3 -> 0.6.4) [CRAN]

Enter one or more numbers, or an empty line to skip updates: 3
── R CMD build ─────────────────────────────────────────────────────────────────────────────
✔  checking for file 'C:\Users\gy17pls\AppData\Local\Temp\RtmpCMQq3o\remotes4aa82b83194b\IamKDO-GADMTools-b9d2503/DESCRIPTION' (627ms)
─  preparing 'GADMTools': (629ms)
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a 'data/datalist' file should be added
─  building 'GADMTools_3.9-1.tar.gz'
   
ERROR: dependencies 'rgdal', 'maptools', 'rgeos' are not available for package 'GADMTools'
* removing 'C:/Program Files/R/R-4.2.3/library/GADMTools'
Warning message:
In i.p(...) :
  installation of package ‘C:/Users/gy17pls/AppData/Local/Temp/RtmpCMQq3o/file4aa85c67f21/GADMTools_3.9-1.tar.gz’ had non-zero exit status

**Comment by toledobastos** [comment]
You may want to first install the dependencies.
